Sitename = 'Blocko Loco'
Useragent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ↪\Chrome/74.0.3729.169 Safari/537.36'
CategoriesUri = 'https://www.blocket.se/stockholm?ca=11'
RegionsUri = 'https://www.blocket.se/'
MaxAge = 10
Port = 8081
Debug = false
